import type { Metadata } from 'next'
import 'crm-project-ui/index.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="text-neutral-700!" lang="en">
      <body>{children}</body>
    </html>
  )
}
